export const UPDATE_CHANNEL = 'UPDATE_CHANNEL';
export const UPDATE_CHANNEL_SUCCESS = 'UPDATE_CHANNEL_SUCCESS';
export const UPDATE_CHANNEL_FAIL = 'UPDATE_CHANNEL_FAIL';
export const GET_DATA_FROM_FILE = 'GET_DATA_FROM_FILE';
export const SAVE_FILE = 'SAVE_FILE';
